# Working with Excel Files

In [1]:
import pandas as pd

In [57]:
df = pd.read_excel('Tokyo-Olympic-Sample-Data.xlsx')
df

,Rank,Team/NOC,Gold,Silver,Bronze,Total,Rank by Total
0,1,United States of America,39,41,33,113,1
1,2,People's Republic of China,38,32,18,88,2
2,3,Japan,27,14,17,58,5
3,4,Great Britain,22,21,22,65,4
4,5,ROC,20,28,23,71,3
...,...,...,...,...,...,...,...
88,86,Ghana,0,0,1,1,77
89,86,Grenada,0,0,1,1,77
90,86,Kuwait,0,0,1,1,77
91,86,Republic of Moldova,0,0,1,1,77
92,86,Syrian Arab Republic,0,0,1,1,77

In [59]:
df = pd.read_excel('Tokyo-Olympic-Sample-Data.xlsx', index_col = 'Rank')
df

                        Team/NOC  Gold  Silver  Bronze  Total  Rank by Total
Rank
1       United States of America    39      41      33    113              1
2     People's Republic of China    38      32      18     88              2
3                          Japan    27      14      17     58              5
4                  Great Britain    22      21      22     65              4
5                            ROC    20      28      23     71              3
...                          ...   ...     ...     ...    ...            ...
86                         Ghana     0       0       1      1             77
86                       Grenada     0       0       1      1             77
86                        Kuwait     0       0       1      1             77
86           Republic of Moldova     0       0       1      1             77
86          Syrian Arab Republic     0       0       1      1             77

[93 rows x 6 columns]